baseURL = 'https:/vipverona.org/'
languageCode = 'it-it'
title = 'Vip Verona ODV'
theme = "ananke"
enableEmoji = true


[params]
  author = "Vip Verona ODV"
  favicon = "logo-vip-vr.png"
  site_logo = "logo-vip-vr.png"
  description = "Vip Verona ODV"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-red"
  body_classes = "avenir bg-white"
  recent_posts_number = 3
  text_color = "red"
  date_format = "2. January 2006"

[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/vipveronaodv/about"
[[params.ananke_socials]] 
  name = "instagram"
  url = "https://www.instagram.com/vip_verona_clown"


[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
[[menu.main]]
  identifier = 'chisiamo'
  name = 'Chi Siamo'
  url = '/chisiamo/'
[[menu.main]]
  identifier = 'contatti'
  name = 'Contatti'
  url = '/contatti/'
[[menu.main]]
  identifier = 'diventareclown'
  name = 'Diventa Clown'
  url = '/diventareclown/'
[[menu.main]]
  identifier = 'sostienici'
  name = 'Sostienici'
  url = '/sostienici/'
[[menu.main]]
  identifier = 'news'
  name = 'News'
  url = '/news/'
