#baseURL = 'https:/vipverona.org/'
languageCode = 'it'
title = 'Vip Verona ODV - Associazione di clownterapia'
theme = "ananke"
enableEmoji = true


[params]
  author = "Vip Verona ODV"
  favicon = "logo-vip-vr-ritaglio.png"
  site_logo = "logo-vip-vr-ritaglio.png"
  description = "Vip Verona ODV"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-red"
  body_classes = "avenir bg-white"
  recent_posts_number = 3
  text_color = "red"
  date_format = "2. January 2006"

[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/vipveronaodv/about"
[[params.ananke_socials]] 
  name = "instagram"
  url = "https://www.instagram.com/vip_verona_clown"


[menu]
[[menu.main]]
  name = 'Chisiamo'
  pageRef = '/chisiamo'
  weight = 100
[[menu.main]]
  name = 'Clownterapia'
  pageRef = '/cosafacciamo'
  weight = 130
[[menu.main]]
  name = 'Valori Vip'
  pageRef = '/valori'
  weight = 150
[[menu.main]]
  name = 'Come Riconoscerci'
  pageRef = '/comericonoscerci'
  weight = 170
[[menu.main]]
  name = 'Federazione'
  pageRef = '/federazionevip'
  weight = 200
[[menu.main]]
  name = 'Contatti'
  pageRef = '/contatti'
  weight = 300
[[menu.main]]
  name = 'Sostienici'
  pageRef = '/sostienici'
  weight = 400
[[menu.main]]
  name = 'Diventaclown'
  pageRef = '/diventareclown'
  weight = 500
[[menu.main]]
  name = 'News'
  pageRef = '/news'
  weight = 600
